baseURL: https://marianna-taki.netlify.app
languageCode: en-us
title: Marianna
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner: 
    buttonText: More about me
    subtitle: 
      
    title: Marianna Taki
  blog: {}
  contact:
    address:
      - city: London
        country: United kingdom
        street: Regent's Park, NW1 4SA
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: mtaki.mam2022@london.edu
        title: Email
    enable: yes
    phone:
      - phone: 020 7000 7000
        title: Phone
  custom_css: []
  custom_js: []
  description: My personal website
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Company Name
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
      - icon: fa-github
        label: GitHub
        url: https://github.com/marianna-taki
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/marianna-taki/
  image: ''
  name: Your name
  navigation:
    button1:
      - name: BLOGS
        url: blogs
   # button2:
   #   - name: Log In
   #     url: '#'
    links:
      - name: Home
        url: '#'
      - name: ABOUT ME
        url: blogs/marianna
      - name: CV
        url: blogs/cv
    menu: Menu
  #  subtitle: By HTML5 Up
 #   title: Forty
  tiles:
    enable: yes
    showcase:
      - image: pic01.jpg
        subtitle: Biography
        title: About me
        url: blogs/marianna
      - image: wine.jpg
        subtitle: Plots of top 25 drinking countries
        title: Drinking habits acrosss countries
        url: blogs/homework1
      - image: germany.jpg
        subtitle: Plot of 2021 German election polls
        title: German Election Poll
        url: blogs/german_election
      - image: social.jpg
        subtitle: Social media and e-mail usage
        title: General Social Survey
        url: blogs/social_survey
      - image: office.jpg
        subtitle: Is there pay discrimination against females in the workplace?
        title: Omega Plc
        url: blogs/office_info
      - image: cinema.jpg
        subtitle: Steven Spielberg vs Tim Burton
        title: IMDB Ratings
        url: blogs/imdb_ratings
  two:
    buttonText: Find out more
    enable: yes
    subtitle: 
    title: Older Posts
    url: blogs
